kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: immich-machine-learning
  labels:
    app.kubernetes.io/instance: immich
    app.kubernetes.io/name: machine-learning
  namespace: immich
spec:
  storageClassName: longhorn
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "10Gi"
