apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-database
  labels:
    app.kubernetes.io/instance: immich
    app.kubernetes.io/name: database
  namespace: immich
spec:
  instances: 3
  storage:
    size: 1Gi
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:18.0-0.5.3
  postgresql:
    shared_preload_libraries:
      - "vchord.so"
  bootstrap:
    initdb:
      postInitApplicationSQL:
        - CREATE EXTENSION vchord CASCADE;
        - CREATE EXTENSION earthdistance CASCADE;
