{
 "title": "Immich Overview",
 "description": "A dashboard to visualize current status of immich instance on kubernetes cluster.",
 "tags": [
  "immich",
  "immich-charts"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "System Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Immich Version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "target_info{namespace=\"immich\", endpoint=\"metrics-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NodeJS Version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "target_info{namespace=\"immich\", endpoint=\"metrics-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Immich Health",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{namespace=\"immich\", endpoint=\"metrics-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Immich Health",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "up{namespace=\"immich\", endpoint=\"metrics-api\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total Errors (4XX | 5XX)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum by(http_method, http_status_code) (increase(http_server_duration_sum{namespace=\"immich\", endpoint=\"metrics-api\", http_status_code=~\"4.*|5.*\"}[$__rate_interval]))",
     "legendFormat": "{{http_method}} {{http_status_code}}"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "(sum(rate(http_server_duration_count{namespace=\"immich\", endpoint=\"metrics-api\"}[$__rate_interval])) by (http_method, http_status_code)) * $__interval_ms / 1000",
     "legendFormat": "{{http_method}} {{http_status_code}}"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(http_method, http_status_code) (rate(http_server_duration_sum{namespace=\"immich\", endpoint=\"metrics-api\"}[$__rate_interval])) / avg by(http_method, http_status_code) (rate(http_server_duration_count{namespace=\"immich\", endpoint=\"metrics-api\"}[$__rate_interval]))",
     "legendFormat": "{{http_method}} {{http_status_code}}"
    }
   ]
  }
 ]
}