apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-loki
  namespace: prometheus-system
  labels:
    grafana_datasource: "1"
data:
  loki-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        url: http://loki:3100
        access: proxy
        isDefault: false