kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: immich-server
  labels:
    app.kubernetes.io/instance: immich
    app.kubernetes.io/name: server
  namespace: immich
spec:
  storageClassName: csi-cinder-retain
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "10Gi"
