apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-server
  labels:
    app.kubernetes.io/instance: immich
    app.kubernetes.io/name: server
  namespace: immich
spec:
  storageClassName: longhorn
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "10Gi"
