apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: immich-valkey
  labels:
    app.kubernetes.io/instance: immich
    app.kubernetes.io/name: valkey
    release: prometheus
  namespace: immich
spec:
  jobLabel: "immich-valkey"
  namespaceSelector:
    matchNames:
      - immich
  selector:
    matchLabels:
      app.kubernetes.io/service: immich-valkey
      app.kubernetes.io/name: valkey
      app.kubernetes.io/instance: immich
  endpoints:
    - port: metrics
      scheme: http
      interval: 30s
      scrapeTimeout: 10s
