kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: immich-valkey
  labels:
    app.kubernetes.io/instance: immich
    app.kubernetes.io/name: valkey
  namespace: immich
spec:
  storageClassName: csi-cinder-delete
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
