apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: prometheus-system
  annotations:
    tailscale.com/proxy-group: ingress-proxies
    tailscale.com/hostname: grafana
spec:
  selector:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: grafana
  ports:
    - name: http
      port: 80
      targetPort: 3000
    - name: https
      port: 443
      targetPort: 3000
  type: LoadBalancer
  loadBalancerClass: tailscale