apiVersion: v1
kind: Service
metadata:
  name: immich
  namespace: immich
  annotations:
    tailscale.com/proxy-group: ingress-proxies
    tailscale.com/hostname: immich
spec:
  selector:
    app.kubernetes.io/controller: main
    app.kubernetes.io/instance: immich
    app.kubernetes.io/name: server
  ports:
    - name: http
      port: 80
      targetPort: 2283
    - name: https
      port: 443
      targetPort: 2283
  type: LoadBalancer
  loadBalancerClass: tailscale