apiVersion: v1
kind: Service
metadata:
  name: immich
  namespace: immich
spec:
  selector:
    app.kubernetes.io/controller: main
    app.kubernetes.io/instance: immich
    app.kubernetes.io/name: server
  ports:
    - name: http
      port: 80
      targetPort: 2283
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: immich
  namespace: immich
  annotations:
    tailscale.com/proxy-group: ingress-proxies
    tailscale.com/hostname: immich
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: immich
      port:
        number: 80
  tls:
    - hosts:
        - immich
